# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 24 Feb 2018 09:41:34 +0000
*               @ALL          1
*               @user         8
